version: '3.8'

services:
  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile-elasticsearch
    container_name: kamikatsu-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data

volumes:
  es-data:
